version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda

  create_conda_env: &create_conda_env
    run:
      name: create conda env
      command: conda create -n kipoi-dev python=3.6

  install_kipoi_utils: &install_kipoi_utils
    run:
      name: Install kipoi_utils
      command: |
        source activate kipoi-dev
        pip install '.[develop]'
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        mkdir test-reports
        source activate kipoi-dev
        py.test --cov=kipoi_utils/ tests/ -n 1 --no-cov-on-fail --junitxml=test-reports/junit.xml
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: |
        source activate kipoi-dev
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports
  
  build_pypi_package: &build_pypi_package
    run:
      name: build python packages
      command: |
        source activate kipoi-dev
        python setup.py sdist bdist_wheel
  conda_install_twine: &conda_install_twine
    run:
      name: Install twine
      command: conda install twine
  pypi_create_pypirc: &pypi_create_pypirc
    run:
      name: init .pypirc
      command: |
        echo -e "[distutils]" >> ~/.pypirc
        echo -e "index-servers = " >> ~/.pypirc
        echo -e "    pypi" >> ~/.pypirc
        echo -e "    testpypi" >> ~/.pypirc
        echo -e "" >> ~/.pypirc
        echo -e "[testpypi]" >> ~/.pypirc
        echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc
        echo -e "username: $TEST_PYPI_USERNAME" >> ~/.pypirc
        echo -e "password: $TEST_PYPI_PASSWORD" >> ~/.pypirc
        echo -e "[pypi]" >> ~/.pypirc
        echo -e "username: $PYPI_USERNAME" >> ~/.pypirc
        echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc

jobs:

  test-py36:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *create_conda_env
      - *install_kipoi_utils
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts

  test-deploy-pypi:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *create_conda_env
      - *install_kipoi_utils
      - *run_tests
      - *build_pypi_package
      - *conda_install_twine
      - *pypi_create_pypirc
      - run:
          name: check if commit is tagged
          command: git describe --exact-match --tags HEAD && echo "commit is tagged; continuing" || circleci step halt
      - run:
          name: upload to TestPyPI
          command: twine upload --repository testpypi dist/* --verbose
      - run:
          name: pip install from TestPyPI
          command: |
            source activate kipoi-dev
            python -m pip install --user --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple kipoi_utils --verbose
            python -c "import kipoi_utils; print(kipoi_utils.__version__)"
    

workflows:
  version: 2

  test-n-deploy:
    jobs:
      - test-py36
      - test-deploy-pypi:
          requires:
            - test-py36
          filters:
            branches:
              only:
                - add-pypi-deployment

